name: Release Build

on:
  push:
    branches: [ "release/*" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable MacOS Desktop
        run: flutter config --enable-macos-desktop

      - name: Build MacOS
        run: flutter build macos --release

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'ApiLens-macOS.zip'
          directory: 'build/macos/Build/Products/Release'
          path: 'ApiLens.app'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ApiLens-macOS
          path: build/macos/Build/Products/Release/ApiLens-macOS.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows --release

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'ApiLens-Windows.zip'
          directory: 'build/windows/runner/release'
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ApiLens-Windows
          path: build/windows/runner/release/ApiLens-Windows.zip
